common/env: Improve helper functions

diff --git a/common/env b/common/env
--- a/common/env
+++ b/common/env
@@ -4,47 +4,72 @@ function check_valid_json {
     python3 -m json.tool $1 >/dev/null 2>&1
 }
 
-function list_proj {
+function uulist {
     find "$PROJ_BASE_PATH"/ -maxdepth 1 -type d -regex ".*/[a-z][^/]*" | grep -o "[a-z0-9-]*$" | grep -v common
 }
 
-function make_all {
+function uumake {
+    cd "$PROJ_BASE_PATH/$1"
+    make clean
+    make
+    if [ "$?" != "0" ]
+    then
+      echo "<<$1>> Make failed"
+      cd -
+      return 1
+    fi
+    check_valid_json manifest.json
+    if [ "$?" != "0" ]
+    then
+      echo "<<$1>> Manifest JSON invalid"
+      cd -
+      return 1
+    fi
+    make install
+    cd -
+}
+
+function uumakeall {
     for p in $(list_proj)
     do
-        cd $p
-        make
-        cd ..
+        echo "+++++++++++++ Building $p +++++++++++++"
+        clean_make_install $p
+        if [ "$?" != "0" ]
+        then
+          echo "<<$p>> Build failed"
+          break
+        fi
     done
 }
 
-function clean_make_install_all {
-    for p in $(list_proj)
-    do
-        cd "$PROJ_BASE_PATH/$p"
-        make clean
-        make
-        if [ "$?" != "0" ]
-        then
-          echo "Make failed for project $p"
-          cd -
-          break
-        fi
-        check_valid_json manifest.json
-        if [ "$?" != "0" ]
-        then
-          echo "Manifest JSON invalid for project $p"
-          cd -
-          break
-        fi
-        make install
-        cd -
-    done
+function get_proj_manifest_name {
+    python3 -c "import json;print(json.load(open('$PROJ_BASE_PATH/$1/manifest.json'))['header']['name'])"
 }
 
-function to_shared {
-    name=$(python3 -c "import json;print(json.load(open('$PROJ_BASE_PATH/$1/manifest.json'))['header']['name'])")
+function uudeploy {
+    name=$(get_proj_manifest_name $1)
     path="$PROJ_BASE_PATH/$1/$name.mnlgxdunit"
     cp "$path" /mnt/shared/
     echo copied $path to /mnt/shared/
 }
 
+function uudist {
+    name=$(get_proj_manifest_name $1)
+    path="$PROJ_BASE_PATH/$1/$name.mnlgxdunit"
+    path2="$PROJ_BASE_PATH/$1/dist/"
+    cp "$path" "$path2"
+    echo copied $path to $path2
+}
+
+function uuhelp {
+    echo "Available functions:"
+    echo "  uuhelp -- Print this message"
+    echo "  uulist -- lists all projects"
+    echo "  uumake <proj> -- runs make, checks manifest.json"
+    echo "                               and runs make install for the selected project"
+    echo "  uumakeall -- runs clean_make_install for all projects"
+    echo "  uudeploy <proj> -- copies the selected project to shared directory"
+    echo "  uudist <proj> -- copies the built binary to dist/"
+}
+
+uuhelp
